[package]
name = "rsampler"
version = "0.1.0"
edition = "2024"
license = "Apache-2.0 OR MIT"

[dependencies]
hound = "3.5"

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
rand_aes = "0.5"

[[bench]]
name = "benchmark_fft"
harness = false

[lib]
bench = false
